set_property IOSTANDARD LVCMOS33 [get_ports audio_lrck]
set_property IOSTANDARD LVCMOS33 [get_ports audio_mclk]
set_property IOSTANDARD LVCMOS33 [get_ports audio_sck]
set_property IOSTANDARD LVCMOS33 [get_ports audio_sdin]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports sw_rst]
set_property PACKAGE_PIN V17 [get_ports sw_rst]
set_property PACKAGE_PIN W5 [get_ports clk_100mhz]
set_property PACKAGE_PIN B16 [get_ports audio_sdin]
set_property PACKAGE_PIN B15 [get_ports audio_sck]
set_property PACKAGE_PIN A14 [get_ports audio_mclk]
set_property PACKAGE_PIN A16 [get_ports audio_lrck]

